### ISSUE TITLE
phantomjs 配合 browsermobproxy 抓取ajax的疑问

### ISSUE THREAD

**Issue by Kevinsssss** [aneasystone/selenium-test#1]
你好, 我使用phantomjs模拟浏览器for循环url列表, 遍历访问url, 但是每次访问完打印har的数据为什么都是之后一条相同的数据 没有别的呢

**Comment by Kevinsssss** [comment]
`
from selenium import webdriver
from browsermobproxy import Server
import json
import re

server = Server('/Users/apple/browsermob-proxy/bin/browsermob-proxy')
server.start()
proxy = server.create_proxy()

proxy_address = "--proxy=127.0.0.1:%s" % proxy.port

proxy.new_har(options={'captureContent': True})

server_args = [proxy_address, '--ignore-ssl-errors=yes', ]

bs = webdriver.PhantomJS(service_args=server_args)

url_list = ['https://market.m.taobao.com/apps/market/content/index.html?contentId=200570811873&feedId=200570811873&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200568937109&feedId=200568937109&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200569009156&feedId=200569009156&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200570791531&feedId=200570791531&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567524051&feedId=200567524051&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567124359&feedId=200567124359&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200569807712&feedId=200569807712&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200570767149&feedId=200570767149&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200568949669&feedId=200568949669&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567124344&feedId=200567124344&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200571374691&feedId=200571374691&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567420843&feedId=200567420843&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200568929198&feedId=200568929198&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567420640&feedId=200567420640&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=toutiao_pingce', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200570322773&feedId=200570322773&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200570418661&feedId=200570418661&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567184619&feedId=200567184619&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200567284890&feedId=200567284890&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline', 'https://market.m.taobao.com/apps/market/content/index.html?contentId=200570571910&feedId=200570571910&wh_weex=true&wx_navbar_transparent=false&data_prefetch=true&business_spm=a2141.7634494&source=topline']

for each in url_list:

    bs.get(each)

    proxy.wait_for_traffic_to_stop(1, 60)

    data_dict = proxy.har

    for each in data_dict['log']['entries']:
        if 'mtop.taobao.beehive.detail.contentservicenewv2' in each['request']['url']:
            if 'mtopjsonp2' in each['response']['content']['text']:
                print(each['response']['content']['text'])
                print('结束一条数据')





server.stop()
bs.quit()`

**Comment by aneasystone** [comment]
@Kevinsssss 你的程序有下面几个问题：
1. `if 'mtopjsonp2' in each['response']['content']['text']` 这个判断条件有问题，应该改成 `if u'调用成功' in each['response']['content']['text']`
2. 每次调用 `bs.get()` 访问一个链接，页面内容都会被追加到 har 文件中，除非调用 `proxy.new_har()` 新生成一个 har 文件，所以不用在每个循环里处理 har，在程序最后处理即可
3. Selenium 的新版本已经停止对 PhantomJS 的支持了，建议换成 Chrome headless

```python
for each in url_list:
    browser.get(each)
    proxy.wait_for_traffic_to_stop(1, 60)

data_dict = proxy.har
for each in data_dict['log']['entries']:
    if 'mtop.taobao.beehive.detail.contentservicenewv2' in each['request']['url']:
        if u'调用成功' in each['response']['content']['text']:
            print(each['response']['content']['text'])
            print('结束一条数据')
```

**Comment by Kevinsssss** [comment]
感谢，电脑没有带回来，明天我再调试一下。我发现每次new_har在mac后台里会有几个java在运行不能结束。pycharm终止了也还在运行，不知道怎么解决。怕会影响爬虫效率占用空间。




| |
18842662595
邮箱：18842662595@163.com
|

签名由 网易邮箱大师 定制

在2018年03月19日 23:41，Desmond Stonie 写道：

@Kevinsssss 你的程序有下面几个问题：

if 'mtopjsonp2' in each['response']['content']['text'] 这个判断条件有问题，应该改成 if u'调用成功' in each['response']['content']['text']
每次调用 bs.get() 访问一个链接，页面内容都会被追加到 har 文件中，除非调用 proxy.new_har() 新生成一个 har 文件，所以不用在每个循环里处理 har，在程序最后处理即可
Selenium 的新版本已经停止对 PhantomJS 的支持了，建议换成 Chrome headless
for each in url_list:
    browser.get(each)
    proxy.wait_for_traffic_to_stop(1, 60)

data_dict = proxy.har
for each in data_dict['log']['entries']:
    if'mtop.taobao.beehive.detail.contentservicenewv2'in each['request']['url']:
        ifu'调用成功'in each['response']['content']['text']:
            print(each['response']['content']['text'])
            print('结束一条数据')

**Comment by aneasystone** [comment]
Hi，@Kevinsssss ，后台的 java 进程并不是 new_har 生成的，而是 `server.start()` 启动的 bmp 进程。

```python
server = Server('browsermob-proxy')
server.start()
```

我在 Windows 系统上也遇到过类似的问题，由于 `server.stop()` 没效果（Mac 可能类似，但我并不确定），导致后台进程一直都存在，而且随着程序每次启动后台的 java 进程会越来越多。

我有两个解决方法：
1. 在每次程序运行结束后，自己遍历 java 的进程并 kill 掉（可能会误杀）；
2. 只需要启动 bmp 服务器一次（可以手动运行），后面执行的时候就不需要 `server.start()` 和 `server.stop()` 了；
